package com.nt.entity;
// Generated 24 May, 2019 6:58:55 PM by Hibernate Tools 5.2.3.Final

/**
 * Insurancepolicy generated by hbm2java
 */
public class Insurancepolicy implements java.io.Serializable {

	private long insuranceid;
	private String insurancename;
	private Long initialamount;
	private Long tenure;

	public Insurancepolicy() {
	}

	public Insurancepolicy(long insuranceid) {
		this.insuranceid = insuranceid;
	}

	public Insurancepolicy(long insuranceid, String insurancename, Long initialamount, Long tenure) {
		this.insuranceid = insuranceid;
		this.insurancename = insurancename;
		this.initialamount = initialamount;
		this.tenure = tenure;
	}

	public long getInsuranceid() {
		return this.insuranceid;
	}

	public void setInsuranceid(long insuranceid) {
		this.insuranceid = insuranceid;
	}

	public String getInsurancename() {
		return this.insurancename;
	}

	public void setInsurancename(String insurancename) {
		this.insurancename = insurancename;
	}

	public Long getInitialamount() {
		return this.initialamount;
	}

	public void setInitialamount(Long initialamount) {
		this.initialamount = initialamount;
	}

	public Long getTenure() {
		return this.tenure;
	}

	public void setTenure(Long tenure) {
		this.tenure = tenure;
	}

	@Override
	public String toString() {
		return "Insurancepolicy [insuranceid=" + insuranceid + ", insurancename=" + insurancename + ", initialamount="
				+ initialamount + ", tenure=" + tenure + "]";
	}
	
	

}
