package com.nt.entity;
// Generated 4 Jun, 2019 9:49:03 AM by Hibernate Tools 5.2.3.Final

/**
 * Vehicle generated by hbm2java
 */
public class Vehicle implements java.io.Serializable {

	private int vid;
	private String type;
	private String model;
	private String company;
	private int price;

	public Vehicle() {
	}

	public Vehicle(int vid) {
		this.vid = vid;
	}

	public Vehicle(int vid, String type, String model, String company, int price) {
		this.vid = vid;
		this.type = type;
		this.model = model;
		this.company = company;
		this.price = price;
	}

	public int getVid() {
		return this.vid;
	}

	public void setVid(int vid) {
		this.vid = vid;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	@Override
	public String toString() {
		return "Vehicle [vid=" + vid + ", type=" + type + ", model=" + model + ", company=" + company + ", price="
				+ price + "]";
	}
	
	

}
